export { default as dir_img } from "../assets/ceo.jpg";
export { default as counsel } from "../assets/counsel.jpg";
export { default as child_counsel } from "../assets/child.jpg";
export { default as doc_img } from "../assets/doctor.jpg";
export { default as therapist_img } from "../assets/therapist.jpg";
export { default as converse } from "../assets/converse.jpg";
export { default as convert } from "../assets/convert.jpg";
export { default as work } from "../assets/work.svg";
export {default as suicide} from "../assets/suicide.jpg";
export {default as art} from "../assets/art.jpg";